blank_issues_enabled: false
contact_links:
  - name: Spoofax Documentation
    url: https://www.spoofax.dev/
    about: Documentation about Spoofax and all included Meta-Languages.
  - name: Spoofax Support Page
    url: https://www.spoofax.dev/support
    about: Information on Spoofax Support, and how to get in touch.
